// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYHrQDMEqtAjG1L4QI848CMT_2F7zXPY0',
    appId: '1:547052785517:web:3fa50bad9ea7f6fb521464',
    messagingSenderId: '547052785517',
    projectId: 'demo1-786b0',
    authDomain: 'demo1-786b0.firebaseapp.com',
    storageBucket: 'demo1-786b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPxkZAMngFHJCdBM2bvSACoNuBFmKHJs0',
    appId: '1:547052785517:android:434abfef2a4895db521464',
    messagingSenderId: '547052785517',
    projectId: 'demo1-786b0',
    storageBucket: 'demo1-786b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK40r5CVFQz9O6yQRiJ2bmG1ejfGH4vIY',
    appId: '1:547052785517:ios:bb73089c03134cfc521464',
    messagingSenderId: '547052785517',
    projectId: 'demo1-786b0',
    storageBucket: 'demo1-786b0.appspot.com',
    androidClientId: '547052785517-1d2spsmjtcrbbtnspajgbq9gomc1627q.apps.googleusercontent.com',
    iosClientId: '547052785517-9m39s2dlf9gd7lmbh9829ncaok2cd8pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoAuth',
  );
}
